/**
 * FanZone Question Bank — 55 templates across 8 categories
 * Based on FanZone_Question_Bank_v2_2.docx (2026-04-02)
 *
 * Template variables: {home_team}, {away_team}, {home_striker}, {away_striker},
 *   {home_midfielder}, {away_midfielder}, {home_keeper}, {away_keeper},
 *   {risky_player_home}, {risky_player_away},
 *   {home_score}, {away_score}, {minute},
 *   {score_option_1}, {score_option_2}, {score_option_3},
 *   {home_sub_striker}, {away_sub_striker}, {sub_midfielder},
 *   {leading_team}, {trailing_team}
 */

export interface QuestionTemplateSeed {
  code: string;
  category: string;
  difficulty: string;
  trigger: string;
  phases: string[];
  textVi: string;
  textEn: string;
  rewardCoins: number;
  answerWindowSec: number;
  options: Array<{ nameVi: string; nameEn: string; emoji: string; defaultPct: number }>;
  resolutionStrategy: string;
  timeoutWindowMin?: number;
  weight: number;
  voidCondition?: string; // Description of when to VOID + refund
}

export const QUESTION_BANK: QuestionTemplateSeed[] = [
  // ═══════════════════════════════════════════════
  //  ⚽  GOAL (14 questions: Q001–Q008, Q031–Q036)
  // ═══════════════════════════════════════════════
  {
    code: 'Q001',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Ai sẽ ghi bàn tiếp theo?',
    textEn: 'Who will score next?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_striker}', nameEn: '{home_striker}', emoji: '⚽', defaultPct: 42 },
      { nameVi: '{away_striker}', nameEn: '{away_striker}', emoji: '⚽', defaultPct: 30 },
      { nameVi: '{home_midfielder}', nameEn: '{home_midfielder}', emoji: '⚽', defaultPct: 16 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', emoji: '⚽', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 100,
  },
  {
    code: 'Q002',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: 'Bàn thắng tiếp theo vào phút nào?',
    textEn: 'When will the next goal be scored?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 30', nameEn: 'Before minute 30', emoji: '⏱️', defaultPct: 22 },
      { nameVi: 'Phút 30–45', nameEn: 'Minute 30–45', emoji: '⏱️', defaultPct: 28 },
      { nameVi: 'Phút 46–65', nameEn: 'Minute 46–65', emoji: '⏱️', defaultPct: 26 },
      { nameVi: 'Sau phút 65', nameEn: 'After minute 65', emoji: '⏱️', defaultPct: 24 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
    voidCondition: 'NO_GOAL_UNTIL_FT',
  },
  {
    code: 'Q003',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1', 'LATE_H2'],
    textVi: 'Có bàn thắng trong 10 phút tới không?',
    textEn: 'Will there be a goal in the next 10 minutes?',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team} ghi', nameEn: 'Yes — {home_team} scores', emoji: '⚽', defaultPct: 38 },
      { nameVi: 'Có — {away_team} ghi', nameEn: 'Yes — {away_team} scores', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goal', emoji: '🚫', defaultPct: 37 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 120,
  },
  {
    code: 'Q004',
    category: 'GOAL',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2', 'LATE_H2'],
    textVi: 'Bàn thắng tiếp theo được ghi bằng cách nào?',
    textEn: 'How will the next goal be scored?',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Đánh đầu — Header', nameEn: 'Header', emoji: '🗣️', defaultPct: 18 },
      { nameVi: 'Sút chân — Normal Goal', nameEn: 'Normal Goal', emoji: '🦶', defaultPct: 63 },
      { nameVi: 'Phạt đền — Penalty', nameEn: 'Penalty', emoji: '⚽', defaultPct: 11 },
      { nameVi: 'Phản lưới — Own Goal', nameEn: 'Own Goal', emoji: '😱', defaultPct: 8 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 40,
    voidCondition: 'NO_GOAL_UNTIL_FT',
  },
  {
    code: 'Q005',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH', 'EARLY_H1'],
    textVi: 'Đội nào ghi bàn trước trong trận?',
    textEn: 'Which team scores first?',
    rewardCoins: 240,
    answerWindowSec: 45,
    options: [
      { nameVi: '{home_team} ghi trước', nameEn: '{home_team} scores first', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team} ghi trước', nameEn: '{away_team} scores first', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goals', emoji: '🚫', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q006',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Tỷ số cuối trận là bao nhiêu?',
    textEn: 'What will the final score be?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{score_option_1}', nameEn: '{score_option_1}', emoji: '📊', defaultPct: 35 },
      { nameVi: '{score_option_2}', nameEn: '{score_option_2}', emoji: '📊', defaultPct: 28 },
      { nameVi: '{score_option_3}', nameEn: '{score_option_3}', emoji: '📊', defaultPct: 22 },
      { nameVi: 'Kết quả khác', nameEn: 'Other result', emoji: '❓', defaultPct: 15 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q007',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H2', 'LATE_H2'],
    textVi: 'Có bàn thắng nào trong phút bù giờ không?',
    textEn: 'Will there be a stoppage time goal?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có, {leading_team} ghi', nameEn: 'Yes, {leading_team} scores', emoji: '⚽', defaultPct: 20 },
      { nameVi: 'Có, {trailing_team} ghi', nameEn: 'Yes, {trailing_team} scores', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', emoji: '🚫', defaultPct: 55 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q008',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Đội nào ghi bàn đầu tiên trong hiệp 2?',
    textEn: 'Who scores first in the second half?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🏠', defaultPct: 46 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '✈️', defaultPct: 34 },
      { nameVi: 'Không ai ghi trước phút 65', nameEn: 'Nobody before minute 65', emoji: '🚫', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q031',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH'],
    textVi: 'Có bàn thắng nào trong hiệp 1 không?',
    textEn: 'Will there be a goal in the first half?',
    rewardCoins: 60,
    answerWindowSec: 45,
    options: [
      { nameVi: 'Có — 1 bàn', nameEn: 'Yes — 1 goal', emoji: '⚽', defaultPct: 35 },
      { nameVi: 'Có — 2 bàn trở lên', nameEn: 'Yes — 2+ goals', emoji: '⚽', defaultPct: 30 },
      { nameVi: 'Không có bàn H1', nameEn: 'No goals in H1', emoji: '🚫', defaultPct: 35 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 100,
  },
  {
    code: 'Q032',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: '{home_striker} có ghi bàn trong trận không?',
    textEn: 'Will {home_striker} score in this match?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có, ghi trong H1', nameEn: 'Yes, scores in H1', emoji: '⚽', defaultPct: 28 },
      { nameVi: 'Có, ghi trong H2', nameEn: 'Yes, scores in H2', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không ghi bàn', nameEn: 'No goal', emoji: '🚫', defaultPct: 47 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q033',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1'],
    textVi: 'Tổng số bàn thắng cả trận là bao nhiêu?',
    textEn: 'How many total goals in the match?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–1 bàn', nameEn: '0–1 goals', emoji: '📉', defaultPct: 20 },
      { nameVi: '2 bàn', nameEn: '2 goals', emoji: '📊', defaultPct: 30 },
      { nameVi: '3 bàn', nameEn: '3 goals', emoji: '📈', defaultPct: 28 },
      { nameVi: '4 bàn trở lên', nameEn: '4+ goals', emoji: '🔥', defaultPct: 22 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q034',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Hiệp 2 có nhiều bàn thắng hơn hiệp 1 không?',
    textEn: 'Will the second half have more goals than the first?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có — H2 nhiều bàn hơn', nameEn: 'Yes — H2 has more', emoji: '📈', defaultPct: 42 },
      { nameVi: 'Không — H1 nhiều hơn hoặc bằng', nameEn: 'No — H1 equal or more', emoji: '📉', defaultPct: 58 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q035',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH'],
    textVi: 'Tỷ số sau 30 phút đầu là bao nhiêu?',
    textEn: 'What will the score be after 30 minutes?',
    rewardCoins: 60,
    answerWindowSec: 45,
    options: [
      { nameVi: '0–0', nameEn: '0–0', emoji: '🤝', defaultPct: 38 },
      { nameVi: '1–0 chủ nhà', nameEn: '1–0 home', emoji: '🏠', defaultPct: 28 },
      { nameVi: '0–1 khách', nameEn: '0–1 away', emoji: '✈️', defaultPct: 22 },
      { nameVi: 'Tỷ số khác', nameEn: 'Other score', emoji: '❓', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 95,
  },
  {
    code: 'Q036',
    category: 'GOAL',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Cầu thủ nào là người kiến tạo bàn thắng tiếp theo?',
    textEn: 'Who will assist the next goal?',
    rewardCoins: 480,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_midfielder}', nameEn: '{home_midfielder}', emoji: '🎯', defaultPct: 25 },
      { nameVi: '{away_midfielder}', nameEn: '{away_midfielder}', emoji: '🎯', defaultPct: 20 },
      { nameVi: '{home_striker} kiến tạo ngược', nameEn: '{home_striker} reverse assist', emoji: '🎯', defaultPct: 15 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', emoji: '🎯', defaultPct: 15 },
      { nameVi: 'Không có kiến tạo / Solo', nameEn: 'No assist / Solo goal', emoji: '⚡', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 35,
  },

  // ═══════════════════════════════════════════════
  //  🟨  CARD (7 questions: Q009–Q013, Q037–Q038)
  // ═══════════════════════════════════════════════
  {
    code: 'Q009',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Có thẻ vàng nào trong 15 phút tới?',
    textEn: 'Yellow card in the next 15 minutes?',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — cầu thủ {home_team}', nameEn: 'Yes — {home_team} player', emoji: '🟨', defaultPct: 28 },
      { nameVi: 'Có — cầu thủ {away_team}', nameEn: 'Yes — {away_team} player', emoji: '🟨', defaultPct: 24 },
      { nameVi: 'Không có thẻ vàng', nameEn: 'No yellow card', emoji: '✅', defaultPct: 48 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 100,
  },
  {
    code: 'Q010',
    category: 'CARD',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có thẻ đỏ nào trong trận không?',
    textEn: 'Will there be a red card?',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — {home_team} bị đuổi', nameEn: 'Yes — {home_team} sent off', emoji: '🟥', defaultPct: 12 },
      { nameVi: 'Có — {away_team} bị đuổi', nameEn: 'Yes — {away_team} sent off', emoji: '🟥', defaultPct: 10 },
      { nameVi: 'Không có thẻ đỏ', nameEn: 'No red card', emoji: '✅', defaultPct: 78 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 30,
  },
  {
    code: 'Q011',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài rút bao nhiêu thẻ vàng còn lại?',
    textEn: 'How many more yellow cards?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: '0 thẻ', nameEn: '0 cards', emoji: '0️⃣', defaultPct: 30 },
      { nameVi: '1 thẻ', nameEn: '1 card', emoji: '1️⃣', defaultPct: 35 },
      { nameVi: '2 thẻ', nameEn: '2 cards', emoji: '2️⃣', defaultPct: 22 },
      { nameVi: '3 thẻ trở lên', nameEn: '3+ cards', emoji: '3️⃣', defaultPct: 13 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q012',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'EVENT_CARD',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ nào nhiều khả năng nhận thẻ tiếp theo?',
    textEn: 'Who is most likely to get the next card?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{risky_player_home}', nameEn: '{risky_player_home}', emoji: '🟨', defaultPct: 35 },
      { nameVi: '{risky_player_away}', nameEn: '{risky_player_away}', emoji: '🟨', defaultPct: 32 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', emoji: '✅', defaultPct: 33 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 90,
    voidCondition: 'NO_CARD_AFTER_CLOSE',
  },
  {
    code: 'Q013',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'EVENT_CARD',
    phases: ['MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ nào nhận thẻ vàng thứ 2 và bị đuổi?',
    textEn: 'Who gets a second yellow and is sent off?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: '{risky_player_home}', nameEn: '{risky_player_home}', emoji: '🟥', defaultPct: 28 },
      { nameVi: '{risky_player_away}', nameEn: '{risky_player_away}', emoji: '🟥', defaultPct: 22 },
      { nameVi: 'Không ai bị đuổi', nameEn: 'Nobody sent off', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },
  {
    code: 'Q037',
    category: 'CARD',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng số thẻ vàng cả trận là bao nhiêu?',
    textEn: 'How many yellow cards total in the match?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–1 thẻ', nameEn: '0–1 cards', emoji: '🟨', defaultPct: 25 },
      { nameVi: '2–3 thẻ', nameEn: '2–3 cards', emoji: '🟨', defaultPct: 42 },
      { nameVi: '4–5 thẻ', nameEn: '4–5 cards', emoji: '🟨', defaultPct: 24 },
      { nameVi: '6 thẻ trở lên', nameEn: '6+ cards', emoji: '🟨', defaultPct: 9 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 95,
  },
  {
    code: 'Q038',
    category: 'CARD',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} hay {away_team} nhận nhiều thẻ hơn?',
    textEn: '{home_team} or {away_team} gets more cards?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} nhận nhiều thẻ hơn', nameEn: '{home_team} gets more', emoji: '🟨', defaultPct: 38 },
      { nameVi: '{away_team} nhận nhiều thẻ hơn', nameEn: '{away_team} gets more', emoji: '🟨', defaultPct: 42 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', emoji: '🤝', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },

  // ═══════════════════════════════════════════════
  //  ⛳  CORNER (6 questions: Q014–Q017, Q039–Q040)
  // ═══════════════════════════════════════════════
  {
    code: 'Q014',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Có phạt góc trong 5 phút tới không?',
    textEn: 'Corner kick in the next 5 minutes?',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team}', nameEn: 'Yes — {home_team}', emoji: '🚩', defaultPct: 36 },
      { nameVi: 'Có — {away_team}', nameEn: 'Yes — {away_team}', emoji: '🚩', defaultPct: 28 },
      { nameVi: 'Không có phạt góc', nameEn: 'No corner', emoji: '🚫', defaultPct: 36 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 5,
    weight: 120,
  },
  {
    code: 'Q015',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Tổng số phạt góc trong hiệp này là bao nhiêu?',
    textEn: 'Total corners this half?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Ít hơn 4', nameEn: 'Less than 4', emoji: '📉', defaultPct: 25 },
      { nameVi: '4–6 phạt góc', nameEn: '4–6 corners', emoji: '📊', defaultPct: 42 },
      { nameVi: '7–9 phạt góc', nameEn: '7–9 corners', emoji: '📈', defaultPct: 24 },
      { nameVi: '10 trở lên', nameEn: '10+', emoji: '🔥', defaultPct: 9 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q016',
    category: 'CORNER',
    difficulty: 'HARD',
    trigger: 'EVENT_CORNER',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Phạt góc tiếp theo có dẫn đến bàn thắng không?',
    textEn: 'Will the next corner lead to a goal?',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — bàn thắng trực tiếp', nameEn: 'Yes — direct goal', emoji: '⚽', defaultPct: 10 },
      { nameVi: 'Có — bàn từ pha 2', nameEn: 'Yes — second phase goal', emoji: '⚽', defaultPct: 15 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', emoji: '🚫', defaultPct: 75 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 3,
    weight: 70,
  },
  {
    code: 'Q017',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Đội nào có nhiều phạt góc hơn sau 10 phút nữa?',
    textEn: 'More corners in the next 10 minutes?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 75,
  },
  {
    code: 'Q039',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng phạt góc cả trận là bao nhiêu?',
    textEn: 'Total corners in the match?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 6', nameEn: 'Under 6', emoji: '📉', defaultPct: 20 },
      { nameVi: '6–9', nameEn: '6–9', emoji: '📊', defaultPct: 38 },
      { nameVi: '10–12', nameEn: '10–12', emoji: '📈', defaultPct: 28 },
      { nameVi: 'Hơn 12', nameEn: 'Over 12', emoji: '🔥', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q040',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} hay {away_team} có nhiều corner hơn cả trận?',
    textEn: '{home_team} or {away_team} more corners overall?',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team} nhiều corner hơn', nameEn: '{home_team} more corners', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team} nhiều corner hơn', nameEn: '{away_team} more corners', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },

  // ═══════════════════════════════════════════════
  //  📺  VAR (6 questions: Q018–Q021, Q041–Q042)
  // ═══════════════════════════════════════════════
  {
    code: 'Q018',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'VAR có được gọi trong 15 phút tới không?',
    textEn: 'Will VAR be called in the next 15 minutes?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — từ chối bàn thắng', nameEn: 'Yes — goal disallowed', emoji: '📺', defaultPct: 18 },
      { nameVi: 'Có — chỉ penalty', nameEn: 'Yes — penalty check', emoji: '📺', defaultPct: 20 },
      { nameVi: 'Có — kiểm tra thẻ đỏ', nameEn: 'Yes — red card check', emoji: '📺', defaultPct: 12 },
      { nameVi: 'Không có VAR', nameEn: 'No VAR', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 70,
  },
  {
    code: 'Q019',
    category: 'VAR',
    difficulty: 'EXPERT',
    trigger: 'EVENT_VAR',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'VAR lật lại quyết định của trọng tài không?',
    textEn: 'Will VAR overturn the decision?',
    rewardCoins: 480,
    answerWindowSec: 60,
    options: [
      { nameVi: 'Có — lật quyết định', nameEn: 'Yes — overturned', emoji: '🔄', defaultPct: 35 },
      { nameVi: 'Không — giữ nguyên', nameEn: 'No — stands', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 50,
    voidCondition: 'NO_VAR_VERDICT_300S',
  },
  {
    code: 'Q020',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có penalty nào được chỉ định trong trận không?',
    textEn: 'Will a penalty be awarded?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có — {home_team} được đá', nameEn: 'Yes — {home_team}', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Có — {away_team} được đá', nameEn: 'Yes — {away_team}', emoji: '⚽', defaultPct: 18 },
      { nameVi: 'Không có penalty', nameEn: 'No penalty', emoji: '🚫', defaultPct: 60 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
  },
  {
    code: 'Q021',
    category: 'VAR',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'VAR có xuất hiện trong 10 phút cuối không?',
    textEn: 'Will VAR appear in the last 10 minutes?',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', emoji: '📺', defaultPct: 35 },
      { nameVi: 'Không', nameEn: 'No', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 80,
  },
  {
    code: 'Q041',
    category: 'VAR',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Có bao nhiêu lần VAR được gọi trong cả trận?',
    textEn: 'How many times will VAR be called in the match?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0 lần', nameEn: '0 times', emoji: '0️⃣', defaultPct: 40 },
      { nameVi: '1 lần', nameEn: '1 time', emoji: '1️⃣', defaultPct: 35 },
      { nameVi: '2 lần', nameEn: '2 times', emoji: '2️⃣', defaultPct: 18 },
      { nameVi: '3 lần trở lên', nameEn: '3+ times', emoji: '3️⃣', defaultPct: 7 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q042',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'EVENT_VAR',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Kết quả lần VAR đang diễn ra là gì?',
    textEn: 'What will be the result of the current VAR review?',
    rewardCoins: 240,
    answerWindowSec: 60,
    options: [
      { nameVi: 'Bàn thắng được công nhận', nameEn: 'Goal confirmed', emoji: '⚽', defaultPct: 45 },
      { nameVi: 'Bàn thắng bị hủy', nameEn: 'Goal cancelled', emoji: '❌', defaultPct: 30 },
      { nameVi: 'Penalty được chỉ định', nameEn: 'Penalty confirmed', emoji: '⚽', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 45,
    voidCondition: 'VAR_PENALTY_CANCELLED_OR_VAR_CARD_OR_NO_VERDICT_180S',
  },

  // ═══════════════════════════════════════════════
  //  🔄  SUB (7 questions: Q022–Q025, Q043–Q045)
  // ═══════════════════════════════════════════════
  {
    code: 'Q022',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào thực hiện thay người đầu tiên?',
    textEn: 'Which team substitutes first?',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🔄', defaultPct: 54 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '🔄', defaultPct: 46 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 110,
    voidCondition: 'NO_SUB_UNTIL_FT',
  },
  {
    code: 'Q023',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Tổng số thay người trong hiệp 2 là bao nhiêu?',
    textEn: 'Total subs in the second half?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–4 người', nameEn: '0–4 subs', emoji: '3️⃣', defaultPct: 18 },
      { nameVi: '5–6 người', nameEn: '5–6 subs', emoji: '5️⃣', defaultPct: 28 },
      { nameVi: '7–8 người', nameEn: '7–8 subs', emoji: '7️⃣', defaultPct: 32 },
      { nameVi: '9–10 người', nameEn: '9–10 subs', emoji: '🔟', defaultPct: 22 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q024',
    category: 'SUB',
    difficulty: 'HARD',
    trigger: 'EVENT_SUB',
    phases: ['EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ vào thay có ghi bàn không?',
    textEn: 'Will the substitute score?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — ghi bàn', nameEn: 'Yes — scores', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Không ghi bàn', nameEn: 'No goal', emoji: '❌', defaultPct: 78 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },
  {
    code: 'Q025',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H2', 'MID_H2'],
    textVi: 'Khi nào diễn ra thay người tiếp theo?',
    textEn: 'When is the next substitution?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 60', nameEn: 'Before minute 60', emoji: '⏱️', defaultPct: 20 },
      { nameVi: 'Phút 60–70', nameEn: 'Minute 60–70', emoji: '⏱️', defaultPct: 32 },
      { nameVi: 'Phút 71–80', nameEn: 'Minute 71–80', emoji: '⏱️', defaultPct: 30 },
      { nameVi: 'Sau phút 80', nameEn: 'After minute 80', emoji: '⏱️', defaultPct: 18 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
    voidCondition: 'NO_SUB_UNTIL_FT',
  },
  {
    code: 'Q043',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Thay người đầu tiên của {home_team} trong H2 là phút nào?',
    textEn: 'When is {home_team}\'s first sub in H2?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Phút 46 (cùng HT)', nameEn: 'Minute 46 (at HT)', emoji: '⏱️', defaultPct: 30 },
      { nameVi: 'Phút 55–65', nameEn: 'Minute 55–65', emoji: '⏱️', defaultPct: 35 },
      { nameVi: 'Phút 66–75', nameEn: 'Minute 66–75', emoji: '⏱️', defaultPct: 25 },
      { nameVi: 'Sau phút 75', nameEn: 'After minute 75', emoji: '⏱️', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
    voidCondition: 'HOME_ALREADY_SUBBED_H1_OR_NO_HOME_SUB_H2',
  },
  {
    code: 'Q044',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H2'],
    textVi: 'Cầu thủ nào được thay vào trong 15 phút tới?',
    textEn: 'Who will be substituted in the next 15 minutes?',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: '{home_sub_striker}', nameEn: '{home_sub_striker}', emoji: '🔄', defaultPct: 35 },
      { nameVi: '{away_sub_striker}', nameEn: '{away_sub_striker}', emoji: '🔄', defaultPct: 30 },
      { nameVi: '{sub_midfielder}', nameEn: '{sub_midfielder}', emoji: '🔄', defaultPct: 20 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', emoji: '🔄', defaultPct: 15 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 65,
    voidCondition: 'NO_SUB_IN_WINDOW',
  },
  {
    code: 'Q045',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} thay người tổng cộng bao nhiêu lần cả trận?',
    textEn: 'How many total subs for {home_team} in the match?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–2 lần', nameEn: '0–2 subs', emoji: '📉', defaultPct: 12 },
      { nameVi: '3 lần', nameEn: '3 subs', emoji: '3️⃣', defaultPct: 22 },
      { nameVi: '4 lần', nameEn: '4 subs', emoji: '4️⃣', defaultPct: 32 },
      { nameVi: '5 lần (tối đa)', nameEn: '5 subs (max)', emoji: '5️⃣', defaultPct: 34 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },

  // ═══════════════════════════════════════════════
  //  ⏱  TIME (5 questions: Q026–Q027, Q046–Q048)
  // ═══════════════════════════════════════════════
  {
    code: 'Q026',
    category: 'TIME',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài bù thêm bao nhiêu phút?',
    textEn: 'How many minutes of stoppage time?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '1–3 phút', nameEn: '1–3 minutes', emoji: '⏱️', defaultPct: 18 },
      { nameVi: '4–5 phút', nameEn: '4–5 minutes', emoji: '⏱️', defaultPct: 40 },
      { nameVi: '6–7 phút', nameEn: '6–7 minutes', emoji: '⏱️', defaultPct: 28 },
      { nameVi: '8 phút trở lên', nameEn: '8+ minutes', emoji: '⏱️', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q027',
    category: 'TIME',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Có bàn thắng nào trong giờ bù không?',
    textEn: 'Goal in stoppage time?',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', emoji: '⚽', defaultPct: 30 },
      { nameVi: 'Không', nameEn: 'No', emoji: '🚫', defaultPct: 70 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q046',
    category: 'TIME',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1'],
    textVi: 'Bù giờ hiệp 1 là bao nhiêu phút?',
    textEn: 'How many minutes of H1 stoppage time?',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: '0–1 phút', nameEn: '0–1 minutes', emoji: '⏱️', defaultPct: 20 },
      { nameVi: '2–3 phút', nameEn: '2–3 minutes', emoji: '⏱️', defaultPct: 45 },
      { nameVi: '4–5 phút', nameEn: '4–5 minutes', emoji: '⏱️', defaultPct: 28 },
      { nameVi: '6 phút trở lên', nameEn: '6+ minutes', emoji: '⏱️', defaultPct: 7 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q047',
    category: 'TIME',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng thời gian bù giờ cả trận (H1+H2) là bao nhiêu?',
    textEn: 'Total stoppage time in the match (H1+H2)?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 5 phút', nameEn: 'Under 5 minutes', emoji: '⏱️', defaultPct: 15 },
      { nameVi: '5–8 phút', nameEn: '5–8 minutes', emoji: '⏱️', defaultPct: 38 },
      { nameVi: '9–12 phút', nameEn: '9–12 minutes', emoji: '⏱️', defaultPct: 32 },
      { nameVi: 'Hơn 12 phút', nameEn: 'Over 12 minutes', emoji: '⏱️', defaultPct: 15 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
  },
  {
    code: 'Q048',
    category: 'TIME',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trận có đi vào hiệp phụ không?',
    textEn: 'Will the match go to extra time?',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — vào extra time', nameEn: 'Yes — extra time', emoji: '⏱️', defaultPct: 35 },
      { nameVi: 'Không — kết thúc trong 90 phút', nameEn: 'No — ends in 90 min', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },

  // ═══════════════════════════════════════════════
  //  📊  STAT (5 questions: Q028–Q029, Q049–Q051)
  // ═══════════════════════════════════════════════
  {
    code: 'Q028',
    category: 'STAT',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào kiểm soát bóng nhiều hơn sau 90 phút?',
    textEn: 'Which team has more possession at full time?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} trên 55%', nameEn: '{home_team} over 55%', emoji: '📊', defaultPct: 42 },
      { nameVi: '{away_team} trên 55%', nameEn: '{away_team} over 55%', emoji: '📊', defaultPct: 30 },
      { nameVi: 'Cân bằng 45–55%', nameEn: 'Balanced 45–55%', emoji: '⚖️', defaultPct: 28 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q029',
    category: 'STAT',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: 'Tổng số cú sút trong cả trận là bao nhiêu?',
    textEn: 'Total shots in the match?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 20 cú sút', nameEn: 'Under 20 shots', emoji: '📉', defaultPct: 20 },
      { nameVi: '20–27 cú sút', nameEn: '20–27 shots', emoji: '📊', defaultPct: 42 },
      { nameVi: '28–34 cú sút', nameEn: '28–34 shots', emoji: '📈', defaultPct: 26 },
      { nameVi: 'Trên 34 cú sút', nameEn: 'Over 34 shots', emoji: '🔥', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q049',
    category: 'STAT',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['MID_H1'],
    textVi: 'Đội nào có nhiều cú sút trúng đích hơn?',
    textEn: 'Which team has more shots on target?',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🎯', defaultPct: 52 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '🎯', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q050',
    category: 'STAT',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Possession của {home_team} trong H1 là bao nhiêu?',
    textEn: '{home_team} possession in H1?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 45%', nameEn: 'Under 45%', emoji: '📉', defaultPct: 25 },
      { nameVi: '45–55%', nameEn: '45–55%', emoji: '📊', defaultPct: 38 },
      { nameVi: 'Trên 55%', nameEn: 'Over 55%', emoji: '📈', defaultPct: 37 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q051',
    category: 'STAT',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng cú sút 2 đội trong H1 là bao nhiêu?',
    textEn: 'Total shots by both teams in H1?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Dưới 8', nameEn: 'Under 8', emoji: '📉', defaultPct: 18 },
      { nameVi: '8–12', nameEn: '8–12', emoji: '📊', defaultPct: 40 },
      { nameVi: '13–17', nameEn: '13–17', emoji: '📈', defaultPct: 28 },
      { nameVi: 'Hơn 17', nameEn: 'Over 17', emoji: '🔥', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },

  // ═══════════════════════════════════════════════
  //  📈  MOMENTUM (5 questions: Q030, Q052–Q055)
  // ═══════════════════════════════════════════════
  {
    code: 'Q030',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Đội nào tạo ra bước ngoặt sau nghỉ giữa hiệp?',
    textEn: 'Who creates the turning point after half-time?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} — tấn công mạnh hơn', nameEn: '{home_team} — stronger attack', emoji: '🔥', defaultPct: 48 },
      { nameVi: '{away_team} — phản công hiệu quả', nameEn: '{away_team} — effective counter', emoji: '⚡', defaultPct: 36 },
      { nameVi: 'Không có thay đổi rõ', nameEn: 'No clear change', emoji: '😐', defaultPct: 16 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q052',
    category: 'MOMENTUM',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Đội nào kiểm soát thế trận trong 15 phút đầu?',
    textEn: 'Which team dominates in the first 15 minutes?',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} áp đảo', nameEn: '{home_team} dominates', emoji: '🔥', defaultPct: 45 },
      { nameVi: '{away_team} áp đảo', nameEn: '{away_team} dominates', emoji: '⚡', defaultPct: 30 },
      { nameVi: 'Thế trận cân bằng', nameEn: 'Balanced play', emoji: '⚖️', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q053',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Đội thua có phản công tích cực hơn trong 15 phút cuối?',
    textEn: 'Does the trailing team mount a stronger attack in the last 15 minutes?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — tăng cú sút và tấn công', nameEn: 'Yes — more shots and attacks', emoji: '🔥', defaultPct: 45 },
      { nameVi: 'Không — thế trận không đổi', nameEn: 'No — no change', emoji: '😐', defaultPct: 55 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
    voidCondition: 'SCORE_BECOMES_TIED',
  },
  {
    code: 'Q054',
    category: 'MOMENTUM',
    difficulty: 'HARD',
    trigger: 'EVENT_GOAL',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Đội ghi bàn đầu có tiếp tục kiểm soát trận đấu?',
    textEn: 'Does the first scoring team maintain control?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — tiếp tục áp đảo', nameEn: 'Yes — continues to dominate', emoji: '💪', defaultPct: 40 },
      { nameVi: 'Không — đội kia phản công mạnh', nameEn: 'No — other team fights back', emoji: '⚡', defaultPct: 60 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 55,
  },
  {
    code: 'Q055',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H2'],
    textVi: 'Trong 20 phút cuối, đội nào tạo nhiều cơ hội nguy hiểm hơn?',
    textEn: 'In the last 20 minutes, which team creates more dangerous chances?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{leading_team} — giữ áp lực', nameEn: '{leading_team} — keeps pressure', emoji: '💪', defaultPct: 35 },
      { nameVi: '{trailing_team} — phản công', nameEn: '{trailing_team} — counter-attacks', emoji: '⚡', defaultPct: 45 },
      { nameVi: 'Cả hai đều nguy hiểm', nameEn: 'Both equally dangerous', emoji: '⚖️', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
    voidCondition: 'SCORE_BECOMES_TIED',
  },
];
