/**
 * FanZone Question Bank — 55 templates across 8 categories
 * Based on FanZone_Question_Bank_v2_4.docx (2026-04-16)
 *
 * Languages: Vietnamese (VI), English (EN), Chinese (ZH)
 *
 * Template variables: {home_team}, {away_team}, {home_striker}, {away_striker},
 *   {home_midfielder}, {away_midfielder}, {home_keeper}, {away_keeper},
 *   {risky_player_home}, {risky_player_away},
 *   {home_score}, {away_score}, {minute},
 *   {score_option_1}, {score_option_2}, {score_option_3},
 *   {home_sub_striker}, {away_sub_striker}, {sub_midfielder},
 *   {leading_team}, {trailing_team}
 */

export interface QuestionTemplateSeed {
  code: string;
  category: string;
  difficulty: string;
  trigger: string;
  phases: string[];
  textVi: string;
  textEn: string;
  textZh: string;
  rewardCoins: number;
  answerWindowSec: number;
  options: Array<{ nameVi: string; nameEn: string; nameZh: string; emoji: string; defaultPct: number }>;
  resolutionStrategy: string;
  timeoutWindowMin?: number;
  weight: number;
  voidCondition?: string; // Description of when to VOID + refund
}

export const QUESTION_BANK: QuestionTemplateSeed[] = [
  // ═══════════════════════════════════════════════
  //  ⚽  GOAL (14 questions: Q001–Q008, Q031–Q036)
  // ═══════════════════════════════════════════════
  {
    code: 'Q001',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Ai sẽ ghi bàn tiếp theo?',
    textEn: 'Who will score next?',
    textZh: '下一个进球的是谁？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_striker}', nameEn: '{home_striker}', nameZh: '{home_striker}', emoji: '⚽', defaultPct: 42 },
      { nameVi: '{away_striker}', nameEn: '{away_striker}', nameZh: '{away_striker}', emoji: '⚽', defaultPct: 30 },
      { nameVi: '{home_midfielder}', nameEn: '{home_midfielder}', nameZh: '{home_midfielder}', emoji: '⚽', defaultPct: 16 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', nameZh: '其他球员', emoji: '⚽', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 100,
  },
  {
    code: 'Q002',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: 'Bàn thắng tiếp theo vào phút nào?',
    textEn: 'When will the next goal be scored?',
    textZh: '下一个进球在第几分钟？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 30', nameEn: 'Before minute 30', nameZh: 'Before minute 30', emoji: '⏱️', defaultPct: 22 },
      { nameVi: 'Phút 30–45', nameEn: 'Minute 30–45', nameZh: 'Minute 30–45', emoji: '⏱️', defaultPct: 28 },
      { nameVi: 'Phút 46–65', nameEn: 'Minute 46–65', nameZh: 'Minute 46–65', emoji: '⏱️', defaultPct: 26 },
      { nameVi: 'Sau phút 65', nameEn: 'After minute 65', nameZh: 'After minute 65', emoji: '⏱️', defaultPct: 24 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
    voidCondition: 'NO_GOAL_UNTIL_FT',
  },
  {
    code: 'Q003',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1', 'LATE_H2'],
    textVi: 'Có bàn thắng trong 10 phút tới không?',
    textEn: 'Will there be a goal in the next 10 minutes?',
    textZh: '接下来10分钟内会有进球吗？',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team} ghi', nameEn: 'Yes — {home_team} scores', nameZh: '是 — {home_team} 进球', emoji: '⚽', defaultPct: 38 },
      { nameVi: 'Có — {away_team} ghi', nameEn: 'Yes — {away_team} scores', nameZh: '是 — {away_team} 进球', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goal', nameZh: '没有进球', emoji: '🚫', defaultPct: 37 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 120,
  },
  {
    code: 'Q004',
    category: 'GOAL',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2', 'LATE_H2'],
    textVi: 'Bàn thắng tiếp theo được ghi bằng cách nào?',
    textEn: 'How will the next goal be scored?',
    textZh: '下一个进球将如何打入？',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Đánh đầu — Header', nameEn: 'Header', nameZh: '头球', emoji: '🗣️', defaultPct: 18 },
      { nameVi: 'Sút chân — Normal Goal', nameEn: 'Normal Goal', nameZh: '否rmal Goal', emoji: '🦶', defaultPct: 63 },
      { nameVi: 'Phạt đền — Penalty', nameEn: 'Penalty', nameZh: '点球', emoji: '⚽', defaultPct: 11 },
      { nameVi: 'Phản lưới — Own Goal', nameEn: 'Own Goal', nameZh: 'Own Goal', emoji: '😱', defaultPct: 8 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 40,
    voidCondition: 'NO_GOAL_UNTIL_FT',
  },
  {
    code: 'Q005',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH', 'EARLY_H1'],
    textVi: 'Đội nào ghi bàn trước trong trận?',
    textEn: 'Which team will score first?',
    textZh: '哪支球队会率先进球？',
    rewardCoins: 240,
    answerWindowSec: 45,
    options: [
      { nameVi: '{home_team} ghi trước', nameEn: '{home_team} scores first', nameZh: '{home_team} 进球 first', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team} ghi trước', nameEn: '{away_team} scores first', nameZh: '{away_team} 进球 first', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goals', nameZh: '没有进球', emoji: '🚫', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q006',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Tỷ số cuối trận là bao nhiêu?',
    textEn: 'What will the final score be?',
    textZh: '比赛最终比分是多少？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{score_option_1}', nameEn: '{score_option_1}', nameZh: '{score_option_1}', emoji: '📊', defaultPct: 35 },
      { nameVi: '{score_option_2}', nameEn: '{score_option_2}', nameZh: '{score_option_2}', emoji: '📊', defaultPct: 28 },
      { nameVi: '{score_option_3}', nameEn: '{score_option_3}', nameZh: '{score_option_3}', emoji: '📊', defaultPct: 22 },
      { nameVi: 'Kết quả khác', nameEn: 'Other result', nameZh: 'Other result', emoji: '❓', defaultPct: 15 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q007',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1'],
    textVi: 'Có bàn thắng nào ở phút bù giờ hiệp 1 không?',
    textEn: 'Will there be a goal in 1st half stoppage time?',
    textZh: '上半场补时是否会有进球？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — có bàn trong bù giờ H1', nameEn: 'Yes — H1 stoppage goal', nameZh: '是 — H1 stoppage goal', emoji: '⚽', defaultPct: 18 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', nameZh: '没有进球', emoji: '🚫', defaultPct: 82 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q008',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Đội nào ghi bàn đầu tiên trong hiệp 2?',
    textEn: 'Which team will score first in the 2nd half?',
    textZh: '哪支球队会在下半场率先进球？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', nameZh: '{home_team}', emoji: '🏠', defaultPct: 46 },
      { nameVi: '{away_team}', nameEn: '{away_team}', nameZh: '{away_team}', emoji: '✈️', defaultPct: 34 },
      { nameVi: 'Không ai ghi trước phút 65', nameEn: 'Nobody before minute 65', nameZh: '65分钟前无人进球', emoji: '🚫', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q031',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH'],
    textVi: 'Có bàn thắng nào trong hiệp 1 không?',
    textEn: 'Will there be any goals in the first half?',
    textZh: '上半场会有进球吗？',
    rewardCoins: 60,
    answerWindowSec: 45,
    options: [
      { nameVi: 'Có — 1 bàn', nameEn: 'Yes — 1 goal', nameZh: '是 — 1 goal', emoji: '⚽', defaultPct: 35 },
      { nameVi: 'Có — 2 bàn trở lên', nameEn: 'Yes — 2+ goals', nameZh: '是 — 2+ goals', emoji: '⚽', defaultPct: 30 },
      { nameVi: 'Không có bàn H1', nameEn: 'No goals in H1', nameZh: '没有进球 in H1', emoji: '🚫', defaultPct: 35 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 100,
  },
  {
    code: 'Q032',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: '{home_striker} có ghi bàn trong trận không?',
    textEn: 'Will {Home Striker} score in this match?',
    textZh: '{主队前锋}会在本场比赛中进球吗？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có, ghi trong H1', nameEn: 'Yes, scores in H1', nameZh: '是，上半场进球', emoji: '⚽', defaultPct: 28 },
      { nameVi: 'Có, ghi trong H2', nameEn: 'Yes, scores in H2', nameZh: '是，下半场进球', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không ghi bàn', nameEn: 'No goal', nameZh: '没有进球', emoji: '🚫', defaultPct: 47 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q033',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1'],
    textVi: 'Tổng số bàn thắng cả trận là bao nhiêu?',
    textEn: 'How many total goals will be scored?',
    textZh: '全场比赛总进球数是多少？',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–1 bàn', nameEn: '0–1 goals', nameZh: '0–1个进球', emoji: '📉', defaultPct: 20 },
      { nameVi: '2 bàn', nameEn: '2 goals', nameZh: '2个进球', emoji: '📊', defaultPct: 30 },
      { nameVi: '3 bàn', nameEn: '3 goals', nameZh: '3个进球', emoji: '📈', defaultPct: 28 },
      { nameVi: '4 bàn trở lên', nameEn: '4+ goals', nameZh: '4个以上进球', emoji: '🔥', defaultPct: 22 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q034',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Hiệp 2 có nhiều bàn thắng hơn hiệp 1 không?',
    textEn: 'Will the 2nd half have more goals than the 1st?',
    textZh: '下半场进球数会多于上半场吗？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có — H2 nhiều bàn hơn', nameEn: 'Yes — H2 has more', nameZh: '是 — 下半场更多', emoji: '📈', defaultPct: 42 },
      { nameVi: 'Không — H1 nhiều hơn hoặc bằng', nameEn: 'No — H1 equal or more', nameZh: '否 — 上半场相同或更多', emoji: '📉', defaultPct: 58 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q035',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH'],
    textVi: 'Tỷ số sau 30 phút đầu là bao nhiêu?',
    textEn: 'What will the score be after the first 30 minutes?',
    textZh: '前30分钟后的比分是多少？',
    rewardCoins: 60,
    answerWindowSec: 45,
    options: [
      { nameVi: '0–0', nameEn: '0–0', nameZh: '0–0', emoji: '🤝', defaultPct: 38 },
      { nameVi: '1–0 chủ nhà', nameEn: '1–0 home', nameZh: '1–0 home', emoji: '🏠', defaultPct: 28 },
      { nameVi: '0–1 khách', nameEn: '0–1 away', nameZh: '0–1 away', emoji: '✈️', defaultPct: 22 },
      { nameVi: 'Tỷ số khác', nameEn: 'Other score', nameZh: '其他比分', emoji: '❓', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 95,
  },
  {
    code: 'Q036',
    category: 'GOAL',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Cầu thủ nào là người kiến tạo bàn thắng tiếp theo?',
    textEn: 'Who will assist the next goal?',
    textZh: '谁将助攻下一个进球？',
    rewardCoins: 480,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_midfielder}', nameEn: '{home_midfielder}', nameZh: '{home_midfielder}', emoji: '🎯', defaultPct: 25 },
      { nameVi: '{away_midfielder}', nameEn: '{away_midfielder}', nameZh: '{away_midfielder}', emoji: '🎯', defaultPct: 20 },
      { nameVi: '{home_striker} kiến tạo ngược', nameEn: '{home_striker} reverse assist', nameZh: '{home_striker} 反向助攻', emoji: '🎯', defaultPct: 15 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', nameZh: '其他球员', emoji: '🎯', defaultPct: 15 },
      { nameVi: 'Không có kiến tạo / Solo', nameEn: 'No assist / Solo goal', nameZh: '否 assist / Solo goal', emoji: '⚡', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 35,
  },

  // ═══════════════════════════════════════════════
  //  🟨  CARD (7 questions: Q009–Q013, Q037–Q038)
  // ═══════════════════════════════════════════════
  {
    code: 'Q009',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Có thẻ vàng nào trong 15 phút tới?',
    textEn: 'Will there be a yellow card in the next 15 minutes?',
    textZh: '接下来15分钟内会有黄牌吗？',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — cầu thủ {home_team}', nameEn: 'Yes — {home_team} player', nameZh: '是 — {home_team} player', emoji: '🟨', defaultPct: 28 },
      { nameVi: 'Có — cầu thủ {away_team}', nameEn: 'Yes — {away_team} player', nameZh: '是 — {away_team} player', emoji: '🟨', defaultPct: 24 },
      { nameVi: 'Không có thẻ vàng', nameEn: 'No yellow card', nameZh: '否 yellow card', emoji: '✅', defaultPct: 48 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 100,
  },
  {
    code: 'Q010',
    category: 'CARD',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có thẻ đỏ nào trong trận không?',
    textEn: 'Will there be a red card in this match?',
    textZh: '本场比赛会有红牌吗？',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — {home_team} bị đuổi', nameEn: 'Yes — {home_team} sent off', nameZh: '是 — {home_team} 被罚下', emoji: '🟥', defaultPct: 12 },
      { nameVi: 'Có — {away_team} bị đuổi', nameEn: 'Yes — {away_team} sent off', nameZh: '是 — {away_team} 被罚下', emoji: '🟥', defaultPct: 10 },
      { nameVi: 'Không có thẻ đỏ', nameEn: 'No red card', nameZh: '没有红牌', emoji: '✅', defaultPct: 78 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 30,
  },
  {
    code: 'Q011',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài rút bao nhiêu thẻ vàng còn lại?',
    textEn: 'How many more yellow cards will be shown?',
    textZh: '裁判还会出示多少张黄牌？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: '0 thẻ', nameEn: '0 cards', nameZh: '0张牌', emoji: '0️⃣', defaultPct: 30 },
      { nameVi: '1 thẻ', nameEn: '1 card', nameZh: '1张牌', emoji: '1️⃣', defaultPct: 35 },
      { nameVi: '2 thẻ', nameEn: '2 cards', nameZh: '2张牌', emoji: '2️⃣', defaultPct: 22 },
      { nameVi: '3 thẻ trở lên', nameEn: '3+ cards', nameZh: '3张以上', emoji: '3️⃣', defaultPct: 13 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q012',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'EVENT_CARD',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ nào nhiều khả năng nhận thẻ tiếp theo?',
    textEn: 'Which player is most likely to receive the next card?',
    textZh: '哪位球员最有可能下一个吃牌？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{risky_player_home}', nameEn: '{risky_player_home}', nameZh: '{risky_player_home}', emoji: '🟨', defaultPct: 35 },
      { nameVi: '{risky_player_away}', nameEn: '{risky_player_away}', nameZh: '{risky_player_away}', emoji: '🟨', defaultPct: 32 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', nameZh: '其他球员', emoji: '✅', defaultPct: 33 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 90,
    voidCondition: 'NO_CARD_AFTER_CLOSE',
  },
  {
    code: 'Q013',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'EVENT_CARD',
    phases: ['MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ nào nhận thẻ vàng thứ 2 và bị đuổi?',
    textEn: 'Which player will receive a 2nd yellow and be sent off?',
    textZh: '哪位球员会吃第二张黄牌被罚下？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: '{risky_player_home}', nameEn: '{risky_player_home}', nameZh: '{risky_player_home}', emoji: '🟥', defaultPct: 28 },
      { nameVi: '{risky_player_away}', nameEn: '{risky_player_away}', nameZh: '{risky_player_away}', emoji: '🟥', defaultPct: 22 },
      { nameVi: 'Không ai bị đuổi', nameEn: 'Nobody sent off', nameZh: '无人 被罚下', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },
  {
    code: 'Q037',
    category: 'CARD',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng số thẻ vàng cả trận là bao nhiêu?',
    textEn: 'How many yellow cards will be shown in total?',
    textZh: '全场比赛共会出示多少张黄牌？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–1 thẻ', nameEn: '0–1 cards', nameZh: '0–1张牌', emoji: '🟨', defaultPct: 25 },
      { nameVi: '2–3 thẻ', nameEn: '2–3 cards', nameZh: '2–3张牌', emoji: '🟨', defaultPct: 42 },
      { nameVi: '4–5 thẻ', nameEn: '4–5 cards', nameZh: '4–5张牌', emoji: '🟨', defaultPct: 24 },
      { nameVi: '6 thẻ trở lên', nameEn: '6+ cards', nameZh: '6张以上', emoji: '🟨', defaultPct: 9 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 95,
  },
  {
    code: 'Q038',
    category: 'CARD',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} hay {away_team} nhận nhiều thẻ hơn?',
    textEn: 'Which team will receive more cards overall?',
    textZh: '{主队}和{客队}哪队会收到更多牌？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} nhận nhiều thẻ hơn', nameEn: '{home_team} gets more', nameZh: '{home_team} 更多', emoji: '🟨', defaultPct: 38 },
      { nameVi: '{away_team} nhận nhiều thẻ hơn', nameEn: '{away_team} gets more', nameZh: '{away_team} 更多', emoji: '🟨', defaultPct: 42 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', nameZh: '相同', emoji: '🤝', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },

  // ═══════════════════════════════════════════════
  //  ⛳  CORNER (6 questions: Q014–Q017, Q039–Q040)
  // ═══════════════════════════════════════════════
  {
    code: 'Q014',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Có phạt góc trong 5 phút tới không?',
    textEn: 'Will there be a corner kick in the next 5 minutes?',
    textZh: '接下来5分钟内会有角球吗？',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team}', nameEn: 'Yes — {home_team}', nameZh: '是 — {home_team}', emoji: '🚩', defaultPct: 36 },
      { nameVi: 'Có — {away_team}', nameEn: 'Yes — {away_team}', nameZh: '是 — {away_team}', emoji: '🚩', defaultPct: 28 },
      { nameVi: 'Không có phạt góc', nameEn: 'No corner', nameZh: '没有角球', emoji: '🚫', defaultPct: 36 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 5,
    weight: 120,
  },
  {
    code: 'Q015',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Tổng số phạt góc trong hiệp này là bao nhiêu?',
    textEn: 'How many corners will there be in this half?',
    textZh: '本半场总共会有多少个角球？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Ít hơn 4', nameEn: 'Less than 4', nameZh: '少于4个', emoji: '📉', defaultPct: 25 },
      { nameVi: '4–6 phạt góc', nameEn: '4–6 corners', nameZh: '4–6个角球', emoji: '📊', defaultPct: 42 },
      { nameVi: '7–9 phạt góc', nameEn: '7–9 corners', nameZh: '7–9个 corners', emoji: '📈', defaultPct: 24 },
      { nameVi: '10 trở lên', nameEn: '10+', nameZh: '10个以上', emoji: '🔥', defaultPct: 9 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q016',
    category: 'CORNER',
    difficulty: 'HARD',
    trigger: 'EVENT_CORNER',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Phạt góc tiếp theo có dẫn đến bàn thắng không?',
    textEn: 'Will the next corner kick lead to a goal?',
    textZh: '下一个角球会导致进球吗？',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — bàn thắng trực tiếp', nameEn: 'Yes — direct goal', nameZh: '是 — direct goal', emoji: '⚽', defaultPct: 10 },
      { nameVi: 'Có — bàn từ pha 2', nameEn: 'Yes — second phase goal', nameZh: '是 — second phase goal', emoji: '⚽', defaultPct: 15 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', nameZh: '没有进球', emoji: '🚫', defaultPct: 75 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 3,
    weight: 70,
  },
  {
    code: 'Q017',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Đội nào có nhiều phạt góc hơn sau 10 phút nữa?',
    textEn: 'Which team will have more corners in the next 10 min?',
    textZh: '再过10分钟，哪队角球数更多？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', nameZh: '{home_team}', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team}', nameEn: '{away_team}', nameZh: '{away_team}', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', nameZh: '相同', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 75,
  },
  {
    code: 'Q039',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng phạt góc cả trận là bao nhiêu?',
    textEn: 'How many total corners in the whole match?',
    textZh: '全场比赛总共会有多少个角球？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 6', nameEn: 'Under 6', nameZh: '少于6个', emoji: '📉', defaultPct: 20 },
      { nameVi: '6–9', nameEn: '6–9', nameZh: '6–9个', emoji: '📊', defaultPct: 38 },
      { nameVi: '10–12', nameEn: '10–12', nameZh: '10–12', emoji: '📈', defaultPct: 28 },
      { nameVi: 'Hơn 12', nameEn: 'Over 12', nameZh: 'Over 12', emoji: '🔥', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q040',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} hay {away_team} có nhiều corner hơn cả trận?',
    textEn: 'Which team will have more corners in the whole match?',
    textZh: '{主队}还是{客队}全场角球数更多？',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team} nhiều corner hơn', nameEn: '{home_team} more corners', nameZh: '{home_team} 更多 corners', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team} nhiều corner hơn', nameEn: '{away_team} more corners', nameZh: '{away_team} 更多 corners', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', nameZh: '相同', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },

  // ═══════════════════════════════════════════════
  //  📺  VAR (6 questions: Q018–Q021, Q041–Q042)
  // ═══════════════════════════════════════════════
  {
    code: 'Q018',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'VAR có được gọi trong 15 phút tới không?',
    textEn: 'Will VAR be called in the next 15 minutes?',
    textZh: '接下来15分钟内会启用VAR吗？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — từ chối bàn thắng', nameEn: 'Yes — goal disallowed', nameZh: '是 — 进球被取消', emoji: '📺', defaultPct: 18 },
      { nameVi: 'Có — chỉ penalty', nameEn: 'Yes — penalty check', nameZh: '是 — 点球判罚审查', emoji: '📺', defaultPct: 20 },
      { nameVi: 'Có — kiểm tra thẻ đỏ', nameEn: 'Yes — red card check', nameZh: '是 — 红牌审查', emoji: '📺', defaultPct: 12 },
      { nameVi: 'Không có VAR', nameEn: 'No VAR', nameZh: '没有VAR', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 70,
  },
  {
    code: 'Q019',
    category: 'VAR',
    difficulty: 'EXPERT',
    trigger: 'EVENT_VAR',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'VAR lật lại quyết định của trọng tài không?',
    textEn: 'Will VAR overturn the referee\'s decision?',
    textZh: 'VAR会推翻裁判的判决吗？',
    rewardCoins: 480,
    answerWindowSec: 60,
    timeoutWindowMin: 5, // v2.3: 300s timeout for VAR verdict
    options: [
      { nameVi: 'Có — lật quyết định', nameEn: 'Yes — overturned', nameZh: '是 — overturned', emoji: '🔄', defaultPct: 35 },
      { nameVi: 'Không — giữ nguyên', nameEn: 'No — stands', nameZh: '否 — stands', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 50,
    voidCondition: 'NO_VAR_VERDICT_300S',
  },
  {
    code: 'Q020',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có penalty nào được chỉ định trong trận không?',
    textEn: 'Will a penalty be awarded in this match?',
    textZh: '本场比赛会判罚点球吗？',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có — {home_team} được đá', nameEn: 'Yes — {home_team}', nameZh: '是 — {home_team}', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Có — {away_team} được đá', nameEn: 'Yes — {away_team}', nameZh: '是 — {away_team}', emoji: '⚽', defaultPct: 18 },
      { nameVi: 'Không có penalty', nameEn: 'No penalty', nameZh: '没有点球', emoji: '🚫', defaultPct: 60 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
  },
  {
    code: 'Q021',
    category: 'VAR',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'VAR có xuất hiện trong 10 phút cuối không?',
    textEn: 'Will VAR be used in the final 10 minutes?',
    textZh: 'VAR会在最后10分钟内被使用吗？',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', nameZh: '是', emoji: '📺', defaultPct: 35 },
      { nameVi: 'Không', nameEn: 'No', nameZh: '否', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 10,
    weight: 80,
  },
  {
    code: 'Q041',
    category: 'VAR',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Có bao nhiêu lần VAR được gọi trong cả trận?',
    textEn: 'How many times will VAR be called in the match?',
    textZh: '全场比赛会启用几次VAR？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0 lần', nameEn: '0 times', nameZh: '0 times', emoji: '0️⃣', defaultPct: 40 },
      { nameVi: '1 lần', nameEn: '1 time', nameZh: '1 time', emoji: '1️⃣', defaultPct: 35 },
      { nameVi: '2 lần', nameEn: '2 times', nameZh: '2 times', emoji: '2️⃣', defaultPct: 18 },
      { nameVi: '3 lần trở lên', nameEn: '3+ times', nameZh: '3+ times', emoji: '3️⃣', defaultPct: 7 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q042',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'EVENT_VAR',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Kết quả lần VAR đang diễn ra là gì?',
    textEn: 'What will the outcome of the current VAR review be?',
    textZh: '当前VAR审查的结果是什么？',
    rewardCoins: 240,
    answerWindowSec: 60,
    options: [
      { nameVi: 'Bàn thắng được công nhận', nameEn: 'Goal confirmed', nameZh: 'Goal confirmed', emoji: '⚽', defaultPct: 45 },
      { nameVi: 'Bàn thắng bị hủy', nameEn: 'Goal cancelled', nameZh: 'Goal cancelled', emoji: '❌', defaultPct: 30 },
      { nameVi: 'Penalty được chỉ định', nameEn: 'Penalty confirmed', nameZh: '点球 confirmed', emoji: '⚽', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 45,
    voidCondition: 'VAR_PENALTY_CANCELLED_OR_VAR_CARD_OR_NO_VERDICT_180S',
  },

  // ═══════════════════════════════════════════════
  //  🔄  SUB (7 questions: Q022–Q025, Q043–Q045)
  // ═══════════════════════════════════════════════
  {
    code: 'Q022',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào thực hiện thay người đầu tiên?',
    textEn: 'Which team will make the first substitution?',
    textZh: '哪支球队会率先换人？',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', nameZh: '{home_team}', emoji: '🔄', defaultPct: 54 },
      { nameVi: '{away_team}', nameEn: '{away_team}', nameZh: '{away_team}', emoji: '🔄', defaultPct: 46 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 110,
    voidCondition: 'NO_SUB_UNTIL_FT',
  },
  {
    code: 'Q023',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Tổng số thay người trong hiệp 2 là bao nhiêu?',
    textEn: 'How many total substitutions in the 2nd half?',
    textZh: '下半场总共会有多少次换人？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–4 người', nameEn: '0–4 subs', nameZh: '0–4次换人', emoji: '3️⃣', defaultPct: 18 },
      { nameVi: '5–6 người', nameEn: '5–6 subs', nameZh: '5–6 subs', emoji: '5️⃣', defaultPct: 28 },
      { nameVi: '7–8 người', nameEn: '7–8 subs', nameZh: '7–8 subs', emoji: '7️⃣', defaultPct: 32 },
      { nameVi: '9–10 người', nameEn: '9–10 subs', nameZh: '9–10 subs', emoji: '🔟', defaultPct: 22 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q024',
    category: 'SUB',
    difficulty: 'HARD',
    trigger: 'EVENT_SUB',
    phases: ['EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ vào thay có ghi bàn không?',
    textEn: 'Will the substitute player score?',
    textZh: '替补球员会进球吗？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — ghi bàn', nameEn: 'Yes — scores', nameZh: '是 — 进球', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Không ghi bàn', nameEn: 'No goal', nameZh: '没有进球', emoji: '❌', defaultPct: 78 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },
  {
    code: 'Q025',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H2', 'MID_H2'],
    textVi: 'Khi nào diễn ra thay người tiếp theo?',
    textEn: 'When will the next substitution happen?',
    textZh: '下一次换人会在什么时候发生？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 60', nameEn: 'Before minute 60', nameZh: '60分钟之前', emoji: '⏱️', defaultPct: 20 },
      { nameVi: 'Phút 60–70', nameEn: 'Minute 60–70', nameZh: '60–70分钟', emoji: '⏱️', defaultPct: 32 },
      { nameVi: 'Phút 71–80', nameEn: 'Minute 71–80', nameZh: '71–80分钟', emoji: '⏱️', defaultPct: 30 },
      { nameVi: 'Sau phút 80', nameEn: 'After minute 80', nameZh: '80分钟之后', emoji: '⏱️', defaultPct: 18 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
    voidCondition: 'NO_SUB_UNTIL_FT',
  },
  {
    code: 'Q043',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Thay người đầu tiên của {home_team} trong H2 là phút nào?',
    textEn: 'When will {Home Team}\'s first H2 substitution be?',
    textZh: '{主队}在下半场的首次换人会在第几分钟？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Phút 46 (cùng HT)', nameEn: 'Minute 46 (at HT)', nameZh: 'Minute 46 (at HT)', emoji: '⏱️', defaultPct: 30 },
      { nameVi: 'Phút 55–65', nameEn: 'Minute 55–65', nameZh: 'Minute 55–65', emoji: '⏱️', defaultPct: 35 },
      { nameVi: 'Phút 66–75', nameEn: 'Minute 66–75', nameZh: 'Minute 66–75', emoji: '⏱️', defaultPct: 25 },
      { nameVi: 'Sau phút 75', nameEn: 'After minute 75', nameZh: 'After minute 75', emoji: '⏱️', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
    voidCondition: 'HOME_ALREADY_SUBBED_H1_OR_NO_HOME_SUB_H2',
  },
  {
    code: 'Q044',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H2'],
    textVi: 'Cầu thủ nào được thay vào trong 15 phút tới?',
    textEn: 'Which type of player will be substituted on next?',
    textZh: '接下来15分钟内，哪位球员会被换上场？',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: '{home_sub_striker}', nameEn: '{home_sub_striker}', nameZh: '{home_sub_striker}', emoji: '🔄', defaultPct: 35 },
      { nameVi: '{away_sub_striker}', nameEn: '{away_sub_striker}', nameZh: '{away_sub_striker}', emoji: '🔄', defaultPct: 30 },
      { nameVi: '{sub_midfielder}', nameEn: '{sub_midfielder}', nameZh: '{sub_midfielder}', emoji: '🔄', defaultPct: 20 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', nameZh: '其他球员', emoji: '🔄', defaultPct: 15 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    timeoutWindowMin: 15,
    weight: 65,
    voidCondition: 'NO_SUB_IN_WINDOW',
  },
  {
    code: 'Q045',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: '{home_team} thay người tổng cộng bao nhiêu lần cả trận?',
    textEn: 'How many total substitutions will {Home Team} make?',
    textZh: '{主队}全场总共会换人几次？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '0–2 lần', nameEn: '0–2 subs', nameZh: '0–2 subs', emoji: '📉', defaultPct: 12 },
      { nameVi: '3 lần', nameEn: '3 subs', nameZh: '3 subs', emoji: '3️⃣', defaultPct: 22 },
      { nameVi: '4 lần', nameEn: '4 subs', nameZh: '4 subs', emoji: '4️⃣', defaultPct: 32 },
      { nameVi: '5 lần (tối đa)', nameEn: '5 subs (max)', nameZh: '5 subs (max)', emoji: '5️⃣', defaultPct: 34 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },

  // ═══════════════════════════════════════════════
  //  ⏱  TIME (5 questions: Q026–Q027, Q046–Q048)
  // ═══════════════════════════════════════════════
  {
    code: 'Q026',
    category: 'TIME',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài bù thêm bao nhiêu phút?',
    textEn: 'How many minutes of stoppage time will be added?',
    textZh: '裁判会补时几分钟？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '1–3 phút', nameEn: '1–3 minutes', nameZh: '1–3分钟', emoji: '⏱️', defaultPct: 18 },
      { nameVi: '4–5 phút', nameEn: '4–5 minutes', nameZh: '4–5 minutes', emoji: '⏱️', defaultPct: 40 },
      { nameVi: '6–7 phút', nameEn: '6–7 minutes', nameZh: '6–7 minutes', emoji: '⏱️', defaultPct: 28 },
      { nameVi: '8 phút trở lên', nameEn: '8+ minutes', nameZh: '8+ minutes', emoji: '⏱️', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q027',
    category: 'TIME',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Có bàn thắng nào trong giờ bù không?',
    textEn: 'Will there be a goal in 2nd half stoppage time?',
    textZh: '下半场补时会有进球吗？',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', nameZh: '是', emoji: '⚽', defaultPct: 30 },
      { nameVi: 'Không', nameEn: 'No', nameZh: '否', emoji: '🚫', defaultPct: 70 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q046',
    category: 'TIME',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1'],
    textVi: 'Bù giờ hiệp 1 là bao nhiêu phút?',
    textEn: 'How many minutes of 1st half stoppage time?',
    textZh: '上半场补时几分钟？',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: '0–1 phút', nameEn: '0–1 minutes', nameZh: '0–1 minutes', emoji: '⏱️', defaultPct: 20 },
      { nameVi: '2–3 phút', nameEn: '2–3 minutes', nameZh: '2–3 minutes', emoji: '⏱️', defaultPct: 45 },
      { nameVi: '4–5 phút', nameEn: '4–5 minutes', nameZh: '4–5 minutes', emoji: '⏱️', defaultPct: 28 },
      { nameVi: '6 phút trở lên', nameEn: '6+ minutes', nameZh: '6+ minutes', emoji: '⏱️', defaultPct: 7 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q047',
    category: 'TIME',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng thời gian bù giờ cả trận (H1+H2) là bao nhiêu?',
    textEn: 'What will total stoppage time (H1+H2) be?',
    textZh: '全场（上下半场）总补时时间是多少？',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 5 phút', nameEn: 'Under 5 minutes', nameZh: '少于5次 minutes', emoji: '⏱️', defaultPct: 15 },
      { nameVi: '5–8 phút', nameEn: '5–8 minutes', nameZh: '5–8次 minutes', emoji: '⏱️', defaultPct: 38 },
      { nameVi: '9–12 phút', nameEn: '9–12 minutes', nameZh: '9–12 minutes', emoji: '⏱️', defaultPct: 32 },
      { nameVi: 'Hơn 12 phút', nameEn: 'Over 12 minutes', nameZh: 'Over 12 minutes', emoji: '⏱️', defaultPct: 15 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
  },
  {
    code: 'Q048',
    category: 'TIME',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'], // Only makes sense when score is tied (checked in engine)
    textVi: 'Trận có đi vào hiệp phụ không?',
    textEn: 'Will the match go to extra time?',
    textZh: '比赛会进入加时赛吗？',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — vào extra time', nameEn: 'Yes — extra time', nameZh: '是 — extra time', emoji: '⏱️', defaultPct: 35 },
      { nameVi: 'Không — kết thúc trong 90 phút', nameEn: 'No — ends in 90 min', nameZh: '否 — ends in 90 min', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },

  // ═══════════════════════════════════════════════
  //  📊  STAT (5 questions: Q028–Q029, Q049–Q051)
  // ═══════════════════════════════════════════════
  {
    code: 'Q028',
    category: 'STAT',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào kiểm soát bóng nhiều hơn sau 90 phút?',
    textEn: 'Which team will have more possession after 90 min?',
    textZh: '90分钟后，哪支球队控球率更高？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} trên 55%', nameEn: '{home_team} over 55%', nameZh: '{home_team} over 55%', emoji: '📊', defaultPct: 42 },
      { nameVi: '{away_team} trên 55%', nameEn: '{away_team} over 55%', nameZh: '{away_team} over 55%', emoji: '📊', defaultPct: 30 },
      { nameVi: 'Cân bằng 45–55%', nameEn: 'Balanced 45–55%', nameZh: 'Balanced 45–55%', emoji: '⚖️', defaultPct: 28 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q029',
    category: 'STAT',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: 'Tổng số cú sút trong cả trận là bao nhiêu?',
    textEn: 'How many total shots will there be in the match?',
    textZh: '全场比赛总共会有多少次射门？',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 20 cú sút', nameEn: 'Under 20 shots', nameZh: 'Under 20 shots', emoji: '📉', defaultPct: 20 },
      { nameVi: '20–27 cú sút', nameEn: '20–27 shots', nameZh: '20–27 shots', emoji: '📊', defaultPct: 42 },
      { nameVi: '28–34 cú sút', nameEn: '28–34 shots', nameZh: '28–34 shots', emoji: '📈', defaultPct: 26 },
      { nameVi: 'Trên 34 cú sút', nameEn: 'Over 34 shots', nameZh: 'Over 34 shots', emoji: '🔥', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q049',
    category: 'STAT',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['MID_H1'],
    textVi: 'Đội nào có nhiều cú sút trúng đích hơn?',
    textEn: 'Which team will have more shots on target?',
    textZh: '哪支球队射正次数更多？',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', nameZh: '{home_team}', emoji: '🎯', defaultPct: 52 },
      { nameVi: '{away_team}', nameEn: '{away_team}', nameZh: '{away_team}', emoji: '🎯', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', nameZh: '相同', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q050',
    category: 'STAT',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Possession của {home_team} trong H1 là bao nhiêu?',
    textEn: 'What will {Home Team}\'s possession be in H1?',
    textZh: '{主队}在上半场的控球率是多少？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 45%', nameEn: 'Under 45%', nameZh: '低于45%', emoji: '📉', defaultPct: 25 },
      { nameVi: '45–55%', nameEn: '45–55%', nameZh: '45–55%', emoji: '📊', defaultPct: 38 },
      { nameVi: 'Trên 55%', nameEn: 'Over 55%', nameZh: '超过55%', emoji: '📈', defaultPct: 37 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q051',
    category: 'STAT',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Tổng cú sút 2 đội trong H1 là bao nhiêu?',
    textEn: 'How many total shots in the 1st half?',
    textZh: '上半场两队总射门次数是多少？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Dưới 8', nameEn: 'Under 8', nameZh: 'Under 8', emoji: '📉', defaultPct: 18 },
      { nameVi: '8–12', nameEn: '8–12', nameZh: '8–12', emoji: '📊', defaultPct: 40 },
      { nameVi: '13–17', nameEn: '13–17', nameZh: '13–17', emoji: '📈', defaultPct: 28 },
      { nameVi: 'Hơn 17', nameEn: 'Over 17', nameZh: 'Over 17', emoji: '🔥', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },

  // ═══════════════════════════════════════════════
  //  📈  MOMENTUM (5 questions: Q030, Q052–Q055)
  // ═══════════════════════════════════════════════
  {
    code: 'Q030',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Đội nào tạo ra bước ngoặt sau nghỉ giữa hiệp?',
    textEn: 'Which team will turn the tide after half-time?',
    textZh: '哪支球队会在中场休息后扭转局面？',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} — tấn công mạnh hơn', nameEn: '{home_team} — stronger attack', nameZh: '{home_team} — — 进攻更强', emoji: '🔥', defaultPct: 48 },
      { nameVi: '{away_team} — phản công hiệu quả', nameEn: '{away_team} — effective counter', nameZh: '{away_team} — — 有效反击', emoji: '⚡', defaultPct: 36 },
      { nameVi: 'Không có thay đổi rõ', nameEn: 'No clear change', nameZh: '没有明显变化', emoji: '😐', defaultPct: 16 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q052',
    category: 'MOMENTUM',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1'],
    textVi: 'Đội nào kiểm soát thế trận trong 15 phút đầu?',
    textEn: 'Which team will dominate the opening 15 minutes?',
    textZh: '哪支球队会主导开场15分钟？',
    rewardCoins: 60,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} áp đảo', nameEn: '{home_team} dominates', nameZh: '{home_team} dominates', emoji: '🔥', defaultPct: 45 },
      { nameVi: '{away_team} áp đảo', nameEn: '{away_team} dominates', nameZh: '{away_team} dominates', emoji: '⚡', defaultPct: 30 },
      { nameVi: 'Thế trận cân bằng', nameEn: 'Balanced play', nameZh: 'Balanced play', emoji: '⚖️', defaultPct: 25 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q053',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Đội thua có phản công tích cực hơn trong 15 phút cuối?',
    textEn: 'Will the losing team counter-press more in the last 15 min?',
    textZh: '落后球队在最后15分钟会更积极反击吗？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — tăng cú sút và tấn công', nameEn: 'Yes — more shots and attacks', nameZh: '是 — 更多 shots and attacks', emoji: '🔥', defaultPct: 45 },
      { nameVi: 'Không — thế trận không đổi', nameEn: 'No — no change', nameZh: '否 — no change', emoji: '😐', defaultPct: 55 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
    voidCondition: 'SCORE_BECOMES_TIED',
  },
  {
    code: 'Q054',
    category: 'MOMENTUM',
    difficulty: 'HARD',
    trigger: 'EVENT_GOAL',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Đội ghi bàn đầu có tiếp tục kiểm soát trận đấu?',
    textEn: 'Will the team that scores first maintain control?',
    textZh: '率先进球的球队会继续控制比赛吗？',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — tiếp tục áp đảo', nameEn: 'Yes — continues to dominate', nameZh: '是 — 继续占据优势', emoji: '💪', defaultPct: 40 },
      { nameVi: 'Không — đội kia phản công mạnh', nameEn: 'No — other team fights back', nameZh: '否 — 对方反击', emoji: '⚡', defaultPct: 60 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 55,
  },
  {
    code: 'Q055',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H2'],
    textVi: 'Trong 20 phút cuối, đội nào tạo nhiều cơ hội nguy hiểm hơn?',
    textEn: 'Which team creates more danger in the last 20 minutes?',
    textZh: '在最后20分钟，哪队会创造更多危险机会？',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{leading_team} — giữ áp lực', nameEn: '{leading_team} — keeps pressure', nameZh: '{leading_team} — keeps pressure', emoji: '💪', defaultPct: 35 },
      { nameVi: '{trailing_team} — phản công', nameEn: '{trailing_team} — counter-attacks', nameZh: '{trailing_team} — counter-attacks', emoji: '⚡', defaultPct: 45 },
      { nameVi: 'Cả hai đều nguy hiểm', nameEn: 'Both equally dangerous', nameZh: 'Both equally dangerous', emoji: '⚖️', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
    voidCondition: 'SCORE_BECOMES_TIED',
  },
];
