/**
 * FanZone Question Bank — 30 templates across 8 categories
 * Based on FanZone_Question_Bank.docx v1.0
 *
 * Template variables: {home_team}, {away_team}, {home_striker}, {away_striker},
 *   {home_keeper}, {away_keeper}, {risky_player_home}, {risky_player_away},
 *   {home_score}, {away_score}, {minute}
 */

export interface QuestionTemplateSeed {
  code: string;
  category: string;
  difficulty: string;
  trigger: string;
  phases: string[];
  textVi: string;
  textEn: string;
  rewardCoins: number;
  answerWindowSec: number;
  options: Array<{ nameVi: string; nameEn: string; emoji: string; defaultPct: number }>;
  resolutionStrategy: string;
  weight: number;
}

export const QUESTION_BANK: QuestionTemplateSeed[] = [
  // ===== GOAL (8 questions: Q001–Q008) =====
  {
    code: 'Q001',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'EVENT_GOAL',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Ai sẽ ghi bàn tiếp theo?',
    textEn: 'Who will score next?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_striker}', nameEn: '{home_striker}', emoji: '⚽', defaultPct: 42 },
      { nameVi: '{away_striker}', nameEn: '{away_striker}', emoji: '⚽', defaultPct: 30 },
      { nameVi: '{home_midfielder}', nameEn: '{home_midfielder}', emoji: '⚽', defaultPct: 16 },
      { nameVi: 'Cầu thủ khác', nameEn: 'Other player', emoji: '⚽', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 100,
  },
  {
    code: 'Q002',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2'],
    textVi: 'Bàn thắng tiếp theo vào phút nào?',
    textEn: 'When will the next goal be scored?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 30', nameEn: 'Before minute 30', emoji: '⏱️', defaultPct: 22 },
      { nameVi: 'Phút 30–45', nameEn: 'Minute 30–45', emoji: '⏱️', defaultPct: 28 },
      { nameVi: 'Phút 46–65', nameEn: 'Minute 46–65', emoji: '⏱️', defaultPct: 26 },
      { nameVi: 'Sau phút 65', nameEn: 'After minute 65', emoji: '⏱️', defaultPct: 24 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q003',
    category: 'GOAL',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['LATE_H1', 'LATE_H2'],
    textVi: 'Có bàn thắng trong 10 phút tới không?',
    textEn: 'Will there be a goal in the next 10 minutes?',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team} ghi', nameEn: 'Yes — {home_team} scores', emoji: '⚽', defaultPct: 38 },
      { nameVi: 'Có — {away_team} ghi', nameEn: 'Yes — {away_team} scores', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goal', emoji: '🚫', defaultPct: 37 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 120,
  },
  {
    code: 'Q004',
    category: 'GOAL',
    difficulty: 'EXPERT',
    trigger: 'EVENT_GOAL',
    phases: ['MID_H1', 'MID_H2', 'LATE_H2'],
    textVi: 'Bàn thắng tiếp theo là đầu hay chân?',
    textEn: 'Next goal: header or foot?',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Đánh đầu', nameEn: 'Header', emoji: '🗣️', defaultPct: 18 },
      { nameVi: 'Chân thuận', nameEn: 'Strong foot', emoji: '🦶', defaultPct: 52 },
      { nameVi: 'Chân trái', nameEn: 'Weak foot', emoji: '🦶', defaultPct: 22 },
      { nameVi: 'Phản lưới', nameEn: 'Own goal', emoji: '😱', defaultPct: 8 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 40,
  },
  {
    code: 'Q005',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['PRE_MATCH', 'EARLY_H1'],
    textVi: 'Đội nào ghi bàn trước trong trận?',
    textEn: 'Which team scores first?',
    rewardCoins: 240,
    answerWindowSec: 45,
    options: [
      { nameVi: '{home_team} ghi trước', nameEn: '{home_team} scores first', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team} ghi trước', nameEn: '{away_team} scores first', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Không có bàn thắng', nameEn: 'No goals', emoji: '🚫', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 90,
  },
  {
    code: 'Q006',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Tỷ số cuối trận là bao nhiêu?',
    textEn: 'What will the final score be?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{score_option_1}', nameEn: '{score_option_1}', emoji: '📊', defaultPct: 35 },
      { nameVi: '{score_option_2}', nameEn: '{score_option_2}', emoji: '📊', defaultPct: 28 },
      { nameVi: '{score_option_3}', nameEn: '{score_option_3}', emoji: '📊', defaultPct: 22 },
      { nameVi: 'Kết quả khác', nameEn: 'Other result', emoji: '❓', defaultPct: 15 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q007',
    category: 'GOAL',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H2', 'LATE_H2'],
    textVi: 'Có bàn thắng nào trong phút bù giờ không?',
    textEn: 'Will there be a stoppage time goal?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có, đội đang dẫn ghi', nameEn: 'Yes, leading team scores', emoji: '⚽', defaultPct: 20 },
      { nameVi: 'Có, đội đang thua ghi', nameEn: 'Yes, trailing team scores', emoji: '⚽', defaultPct: 25 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', emoji: '🚫', defaultPct: 55 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q008',
    category: 'GOAL',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Đội nào ghi bàn đầu tiên trong hiệp 2?',
    textEn: 'Who scores first in the second half?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🏠', defaultPct: 46 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '✈️', defaultPct: 34 },
      { nameVi: 'Không ai ghi trước phút 65', nameEn: 'Nobody before minute 65', emoji: '🚫', defaultPct: 20 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },

  // ===== CARD (5 questions: Q009–Q013) =====
  {
    code: 'Q009',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Có thẻ vàng nào trong 15 phút tới?',
    textEn: 'Yellow card in the next 15 minutes?',
    rewardCoins: 125,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — cầu thủ {home_team}', nameEn: 'Yes — {home_team} player', emoji: '🟨', defaultPct: 28 },
      { nameVi: 'Có — cầu thủ {away_team}', nameEn: 'Yes — {away_team} player', emoji: '🟨', defaultPct: 24 },
      { nameVi: 'Không có thẻ vàng', nameEn: 'No yellow card', emoji: '✅', defaultPct: 48 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 100,
  },
  {
    code: 'Q010',
    category: 'CARD',
    difficulty: 'EXPERT',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có thẻ đỏ nào trong trận không?',
    textEn: 'Will there be a red card?',
    rewardCoins: 480,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — {home_team} bị đuổi', nameEn: 'Yes — {home_team} sent off', emoji: '🟥', defaultPct: 12 },
      { nameVi: 'Có — {away_team} bị đuổi', nameEn: 'Yes — {away_team} sent off', emoji: '🟥', defaultPct: 10 },
      { nameVi: 'Không có thẻ đỏ', nameEn: 'No red card', emoji: '✅', defaultPct: 78 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 30,
  },
  {
    code: 'Q011',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài rút bao nhiêu thẻ vàng còn lại?',
    textEn: 'How many more yellow cards?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: '0 thẻ', nameEn: '0 cards', emoji: '0️⃣', defaultPct: 30 },
      { nameVi: '1 thẻ', nameEn: '1 card', emoji: '1️⃣', defaultPct: 35 },
      { nameVi: '2 thẻ', nameEn: '2 cards', emoji: '2️⃣', defaultPct: 22 },
      { nameVi: '3 thẻ trở lên', nameEn: '3+ cards', emoji: '3️⃣', defaultPct: 13 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q012',
    category: 'CARD',
    difficulty: 'MEDIUM',
    trigger: 'EVENT_CARD',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ nào nhận thẻ tiếp theo?',
    textEn: 'Who gets the next card?',
    rewardCoins: 125,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Cầu thủ {home_team}', nameEn: '{home_team} player', emoji: '🟨', defaultPct: 35 },
      { nameVi: 'Cầu thủ {away_team}', nameEn: '{away_team} player', emoji: '🟨', defaultPct: 32 },
      { nameVi: 'Không ai nhận thẻ', nameEn: 'Nobody', emoji: '✅', defaultPct: 33 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 90,
  },
  {
    code: 'Q013',
    category: 'CARD',
    difficulty: 'HARD',
    trigger: 'EVENT_CARD',
    phases: ['MID_H2', 'LATE_H2'],
    textVi: 'Có cầu thủ nào nhận thẻ vàng thứ 2?',
    textEn: 'Will anyone get a second yellow?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — cầu thủ {home_team}', nameEn: 'Yes — {home_team} player', emoji: '🟥', defaultPct: 28 },
      { nameVi: 'Có — cầu thủ {away_team}', nameEn: 'Yes — {away_team} player', emoji: '🟥', defaultPct: 22 },
      { nameVi: 'Không ai bị đuổi', nameEn: 'Nobody sent off', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },

  // ===== CORNER (4 questions: Q014–Q017) =====
  {
    code: 'Q014',
    category: 'CORNER',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Có phạt góc trong 5 phút tới không?',
    textEn: 'Corner kick in the next 5 minutes?',
    rewardCoins: 60,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — {home_team}', nameEn: 'Yes — {home_team}', emoji: '🚩', defaultPct: 36 },
      { nameVi: 'Có — {away_team}', nameEn: 'Yes — {away_team}', emoji: '🚩', defaultPct: 28 },
      { nameVi: 'Không có phạt góc', nameEn: 'No corner', emoji: '🚫', defaultPct: 36 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 120,
  },
  {
    code: 'Q015',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Tổng số phạt góc trong hiệp này?',
    textEn: 'Total corners this half?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Ít hơn 4', nameEn: 'Less than 4', emoji: '📉', defaultPct: 25 },
      { nameVi: '4–6 phạt góc', nameEn: '4–6 corners', emoji: '📊', defaultPct: 42 },
      { nameVi: '7–9 phạt góc', nameEn: '7–9 corners', emoji: '📈', defaultPct: 24 },
      { nameVi: '10 trở lên', nameEn: '10+', emoji: '🔥', defaultPct: 9 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q016',
    category: 'CORNER',
    difficulty: 'HARD',
    trigger: 'EVENT_CORNER',
    phases: ['EARLY_H1', 'MID_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Phạt góc tiếp theo có dẫn đến bàn thắng?',
    textEn: 'Will the next corner lead to a goal?',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có — bàn trực tiếp', nameEn: 'Yes — direct goal', emoji: '⚽', defaultPct: 10 },
      { nameVi: 'Có — bàn từ pha 2', nameEn: 'Yes — second ball', emoji: '⚽', defaultPct: 15 },
      { nameVi: 'Không có bàn', nameEn: 'No goal', emoji: '🚫', defaultPct: 75 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },
  {
    code: 'Q017',
    category: 'CORNER',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'MID_H2'],
    textVi: 'Đội nào có nhiều phạt góc hơn sau 10 phút?',
    textEn: 'More corners in the next 10 minutes?',
    rewardCoins: 150,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🏠', defaultPct: 52 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '✈️', defaultPct: 38 },
      { nameVi: 'Bằng nhau', nameEn: 'Equal', emoji: '🤝', defaultPct: 10 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },

  // ===== VAR (4 questions: Q018–Q021) =====
  {
    code: 'Q018',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'VAR có được gọi trong 15 phút tới?',
    textEn: 'Will VAR be called in the next 15 minutes?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — từ chối bàn thắng', nameEn: 'Yes — goal disallowed', emoji: '📺', defaultPct: 18 },
      { nameVi: 'Có — chỉ penalty', nameEn: 'Yes — penalty check', emoji: '📺', defaultPct: 20 },
      { nameVi: 'Có — kiểm tra thẻ đỏ', nameEn: 'Yes — red card check', emoji: '📺', defaultPct: 12 },
      { nameVi: 'Không có VAR', nameEn: 'No VAR', emoji: '✅', defaultPct: 50 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 70,
  },
  {
    code: 'Q019',
    category: 'VAR',
    difficulty: 'EXPERT',
    trigger: 'EVENT_VAR',
    phases: ['EARLY_H1', 'MID_H1', 'LATE_H1', 'EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'VAR lật lại quyết định của trọng tài?',
    textEn: 'Will VAR overturn the decision?',
    rewardCoins: 480,
    answerWindowSec: 60,
    options: [
      { nameVi: 'Có — lật quyết định', nameEn: 'Yes — overturned', emoji: '🔄', defaultPct: 35 },
      { nameVi: 'Không — giữ nguyên', nameEn: 'No — stands', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 50,
  },
  {
    code: 'Q020',
    category: 'VAR',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'EARLY_H2', 'MID_H2'],
    textVi: 'Có penalty nào được chỉ định trong trận?',
    textEn: 'Will a penalty be awarded?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Có — {home_team} được đá', nameEn: 'Yes — {home_team}', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Có — {away_team} được đá', nameEn: 'Yes — {away_team}', emoji: '⚽', defaultPct: 18 },
      { nameVi: 'Không có penalty', nameEn: 'No penalty', emoji: '🚫', defaultPct: 60 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 65,
  },
  {
    code: 'Q021',
    category: 'VAR',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'VAR có xuất hiện trong 10 phút cuối?',
    textEn: 'Will VAR appear in the last 10 minutes?',
    rewardCoins: 150,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', emoji: '📺', defaultPct: 35 },
      { nameVi: 'Không', nameEn: 'No', emoji: '✅', defaultPct: 65 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 80,
  },

  // ===== SUB (4 questions: Q022–Q025) =====
  {
    code: 'Q022',
    category: 'SUB',
    difficulty: 'EASY',
    trigger: 'SCHEDULED',
    phases: ['MID_H1', 'HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào thay người đầu tiên?',
    textEn: 'Which team substitutes first?',
    rewardCoins: 60,
    answerWindowSec: 35,
    options: [
      { nameVi: '{home_team}', nameEn: '{home_team}', emoji: '🔄', defaultPct: 54 },
      { nameVi: '{away_team}', nameEn: '{away_team}', emoji: '🔄', defaultPct: 46 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 110,
  },
  {
    code: 'Q023',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Tổng số thay người trong hiệp 2?',
    textEn: 'Total subs in the second half?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '3 thay người', nameEn: '3 subs', emoji: '3️⃣', defaultPct: 18 },
      { nameVi: '4 thay người', nameEn: '4 subs', emoji: '4️⃣', defaultPct: 28 },
      { nameVi: '5 thay người', nameEn: '5 subs', emoji: '5️⃣', defaultPct: 32 },
      { nameVi: '6 người (tối đa)', nameEn: '6 subs (max)', emoji: '6️⃣', defaultPct: 22 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },
  {
    code: 'Q024',
    category: 'SUB',
    difficulty: 'HARD',
    trigger: 'EVENT_SUB',
    phases: ['EARLY_H2', 'MID_H2', 'LATE_H2'],
    textVi: 'Cầu thủ vào thay có ghi bàn không?',
    textEn: 'Will the substitute score?',
    rewardCoins: 240,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Có — ghi bàn', nameEn: 'Yes — scores', emoji: '⚽', defaultPct: 22 },
      { nameVi: 'Không ghi bàn', nameEn: 'No goal', emoji: '❌', defaultPct: 78 },
    ],
    resolutionStrategy: 'TIMEOUT_DEFAULT',
    weight: 60,
  },
  {
    code: 'Q025',
    category: 'SUB',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H2', 'MID_H2'],
    textVi: 'Khi nào thay người tiếp theo?',
    textEn: 'When is the next substitution?',
    rewardCoins: 125,
    answerWindowSec: 35,
    options: [
      { nameVi: 'Trước phút 60', nameEn: 'Before minute 60', emoji: '⏱️', defaultPct: 20 },
      { nameVi: 'Phút 60–70', nameEn: 'Minute 60–70', emoji: '⏱️', defaultPct: 32 },
      { nameVi: 'Phút 71–80', nameEn: 'Minute 71–80', emoji: '⏱️', defaultPct: 30 },
      { nameVi: 'Sau phút 80', nameEn: 'After minute 80', emoji: '⏱️', defaultPct: 18 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },

  // ===== TIME (2 questions: Q026–Q027) =====
  {
    code: 'Q026',
    category: 'TIME',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Trọng tài bù thêm bao nhiêu phút?',
    textEn: 'How many minutes of stoppage time?',
    rewardCoins: 125,
    answerWindowSec: 35,
    options: [
      { nameVi: '1–3 phút', nameEn: '1–3 minutes', emoji: '⏱️', defaultPct: 18 },
      { nameVi: '4–5 phút', nameEn: '4–5 minutes', emoji: '⏱️', defaultPct: 40 },
      { nameVi: '6–7 phút', nameEn: '6–7 minutes', emoji: '⏱️', defaultPct: 28 },
      { nameVi: '8 phút trở lên', nameEn: '8+ minutes', emoji: '⏱️', defaultPct: 14 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
  {
    code: 'Q027',
    category: 'TIME',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['LATE_H2'],
    textVi: 'Có bàn thắng nào trong giờ bù?',
    textEn: 'Goal in stoppage time?',
    rewardCoins: 240,
    answerWindowSec: 30,
    options: [
      { nameVi: 'Có', nameEn: 'Yes', emoji: '⚽', defaultPct: 30 },
      { nameVi: 'Không', nameEn: 'No', emoji: '🚫', defaultPct: 70 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 75,
  },

  // ===== STAT (2 questions: Q028–Q029) =====
  {
    code: 'Q028',
    category: 'STAT',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME', 'EARLY_H2'],
    textVi: 'Đội nào kiểm soát bóng nhiều hơn sau 90 phút?',
    textEn: 'Which team has more possession at full time?',
    rewardCoins: 150,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} trên 55%', nameEn: '{home_team} over 55%', emoji: '📊', defaultPct: 42 },
      { nameVi: '{away_team} trên 55%', nameEn: '{away_team} over 55%', emoji: '📊', defaultPct: 30 },
      { nameVi: 'Cân bằng 45–55%', nameEn: 'Balanced 45–55%', emoji: '⚖️', defaultPct: 28 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 80,
  },
  {
    code: 'Q029',
    category: 'STAT',
    difficulty: 'HARD',
    trigger: 'SCHEDULED',
    phases: ['EARLY_H1', 'MID_H1'],
    textVi: 'Tổng số cú sút trong cả trận?',
    textEn: 'Total shots in the match?',
    rewardCoins: 240,
    answerWindowSec: 40,
    options: [
      { nameVi: 'Dưới 20 cú sút', nameEn: 'Under 20 shots', emoji: '📉', defaultPct: 20 },
      { nameVi: '20–27 cú sút', nameEn: '20–27 shots', emoji: '📊', defaultPct: 42 },
      { nameVi: '28–34 cú sút', nameEn: '28–34 shots', emoji: '📈', defaultPct: 26 },
      { nameVi: 'Trên 34 cú sút', nameEn: 'Over 34 shots', emoji: '🔥', defaultPct: 12 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 70,
  },

  // ===== MOMENTUM (1 question: Q030) =====
  {
    code: 'Q030',
    category: 'MOMENTUM',
    difficulty: 'MEDIUM',
    trigger: 'SCHEDULED',
    phases: ['HALF_TIME'],
    textVi: 'Ai tạo bước ngoặt sau nghỉ giữa hiệp?',
    textEn: 'Who creates the turning point after half-time?',
    rewardCoins: 125,
    answerWindowSec: 40,
    options: [
      { nameVi: '{home_team} — tấn công mạnh hơn', nameEn: '{home_team} — stronger attack', emoji: '🔥', defaultPct: 48 },
      { nameVi: '{away_team} — phản công hiệu quả', nameEn: '{away_team} — effective counter', emoji: '⚡', defaultPct: 36 },
      { nameVi: 'Không có thay đổi rõ', nameEn: 'No clear change', emoji: '😐', defaultPct: 16 },
    ],
    resolutionStrategy: 'AUTO',
    weight: 85,
  },
];
